# Generated by Django (Consolidated after merge conflict)
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaiTro',
            fields=[
                ('VaiTroID', models.AutoField(primary_key=True, serialize=False)),
                ('ChucVu', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Vai Trò',
            },
        ),
        migrations.CreateModel(
            name='DonViBenNgoai',
            fields=[
                ('DonViNgoaiID', models.AutoField(primary_key=True, serialize=False)),
                ('TenDonVi', models.CharField(max_length=100)),
                ('DiaChi', models.CharField(blank=True, max_length=255, null=True)),
                ('SoDienThoai', models.CharField(blank=True, max_length=15, null=True)),
                ('NguoiLienHe', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('SoThuTu', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name_plural': 'Đơn vị bên ngoài',
            },
        ),
        migrations.CreateModel(
            name='DonViBenTrong',
            fields=[
                ('DonViTrongID', models.AutoField(primary_key=True, serialize=False)),
                ('TenDonVi', models.CharField(max_length=100)),
                ('DiaChi', models.CharField(blank=True, max_length=255, null=True)),
                ('SoDienThoai', models.CharField(blank=True, max_length=15, null=True)),
                ('NguoiLienHe', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('SoThuTu', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name_plural': 'Đơn vị bên trong',
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('HoTen', models.CharField(max_length=100)),
                ('SoDienThoai', models.CharField(max_length=15)),
                ('NgaySinh', models.DateField(blank=True, null=True)),
                ('GioiTinh', models.CharField(blank=True, choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], max_length=10, null=True)),
                ('TrangThai', models.BooleanField(default=True)),
                ('SoThuTu', models.IntegerField(blank=True, default=0, null=True)),
                ('PhongBan', models.CharField(blank=True, max_length=100, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('VaiTroID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.vaitro')),
            ],
            options={
                'verbose_name': 'Người dùng',
                'verbose_name_plural': 'Người dùng',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='VanBanDen',
            fields=[
                ('VanBanDenID', models.AutoField(primary_key=True, serialize=False)),
                ('SoKyHieu', models.CharField(max_length=50)),
                ('NgayBanHanh', models.DateTimeField(blank=True, null=True)),
                ('NgayNhan', models.DateTimeField(blank=True, null=True)),
                ('LoaiVanBan', models.CharField(blank=True, max_length=50, null=True)),
                ('TrichYeu', models.CharField(blank=True, max_length=255, null=True)),
                ('TrangThai', models.CharField(choices=[('MOI', 'Mới'), ('HOAN_THANH', 'Hoàn thành'), ('DANG_XU_LY', 'Đang xử lý')], default='DANG_XU_LY', max_length=50)),
                ('TepDinhKem', models.FileField(blank=True, null=True, upload_to='den/%Y/%m/')),
                ('NgayHoanThanh', models.DateTimeField(blank=True, null=True)),
                ('DonViNgoaiID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.donvibenngoai')),
                ('DonViTrongID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.donvibentrong')),
                ('UserID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Văn bản đến',
            },
        ),
        migrations.CreateModel(
            name='VanBanDi',
            fields=[
                ('VanBanDiID', models.AutoField(primary_key=True, serialize=False)),
                ('SoKyHieu', models.CharField(max_length=50)),
                ('NgayBanHanh', models.DateTimeField(blank=True, null=True)),
                ('LoaiVanBan', models.CharField(blank=True, max_length=50, null=True)),
                ('TrichYeu', models.CharField(blank=True, max_length=255, null=True)),
                ('TrangThai', models.CharField(choices=[('DU_THAO', 'Dự thảo'), ('CHO_PHE_DUYET', 'Chờ phê duyệt'), ('DA_PHE_DUYET', 'Đã phê duyệt'), ('DA_PHAT_HANH', 'Đã phát hành')], default='DU_THAO', max_length=50)),
                ('TepDinhKem', models.FileField(blank=True, null=True, upload_to='di/%Y/%m/')),
                ('DonViNgoaiID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.donvibenngoai')),
                ('DonViTrongID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.donvibentrong')),
                ('UserID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Văn bản đi',
            },
        ),
        migrations.CreateModel(
            name='PhanCong',
            fields=[
                ('PhanCongID', models.AutoField(primary_key=True, serialize=False)),
                ('NgayPhanCong', models.DateTimeField(blank=True, null=True)),
                ('HanXuLy', models.DateTimeField(blank=True, null=True)),
                ('MucDoUuTien', models.CharField(blank=True, max_length=50, null=True)),
                ('TrangThaiXuLy', models.CharField(blank=True, max_length=50, null=True)),
                ('GhiChu', models.CharField(blank=True, max_length=255, null=True)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('VanBanDenID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.vanbanden')),
                ('VanBanDiID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.vanbandi')),
            ],
            options={
                'verbose_name_plural': 'Phân công',
            },
        ),
        migrations.CreateModel(
            name='PheDuyet',
            fields=[
                ('PheDuyetID', models.AutoField(primary_key=True, serialize=False)),
                ('NgayPheDuyet', models.DateTimeField(blank=True, null=True)),
                ('TrangThaiDuyet', models.BooleanField(default=False)),
                ('ChuKySo', models.TextField(blank=True, null=True)),
                ('GhiChu', models.TextField(blank=True, null=True)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('VanBanDiID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.vanbandi')),
            ],
            options={
                'verbose_name_plural': 'Phê duyệt',
            },
        ),
        migrations.CreateModel(
            name='PhatHanh',
            fields=[
                ('PhatHanhID', models.AutoField(primary_key=True, serialize=False)),
                ('TieuDe', models.CharField(blank=True, max_length=255, null=True)),
                ('TrangThai', models.CharField(blank=True, max_length=50, null=True)),
                ('NgayPhatHanh', models.DateTimeField(blank=True, null=True)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('VanBanDiID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.vanbandi')),
            ],
            options={
                'verbose_name_plural': 'Phát hành',
            },
        ),
        migrations.CreateModel(
            name='LichSuHoatDong',
            fields=[
                ('LichSuID', models.AutoField(primary_key=True, serialize=False)),
                ('LoaiDoiTuong', models.CharField(blank=True, max_length=50, null=True)),
                ('DoiTuongID', models.IntegerField(blank=True, null=True)),
                ('HanhDong', models.CharField(blank=True, max_length=50, null=True)),
                ('NoiDungThayDoi', models.TextField(blank=True, null=True)),
                ('TrangThaiCu', models.CharField(blank=True, max_length=50, null=True)),
                ('TrangThaiMoi', models.CharField(blank=True, max_length=50, null=True)),
                ('ThoiGianCapNhat', models.DateTimeField(auto_now=True)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Lịch sử hoạt động',
            },
        ),
        migrations.CreateModel(
            name='ChuyenTiep',
            fields=[
                ('ChuyenTiepID', models.AutoField(primary_key=True, serialize=False)),
                ('NgayChuyenTiep', models.DateTimeField(blank=True, null=True)),
                ('NgayBatDau', models.DateTimeField(blank=True, null=True)),
                ('NgayHetHan', models.DateTimeField(blank=True, null=True)),
                ('MucDoUuTien', models.CharField(blank=True, max_length=50, null=True)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('VanBanDenID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.vanbanden')),
                ('VanBanDiID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.vanbandi')),
            ],
            options={
                'verbose_name_plural': 'Chuyển tiếp',
            },
        ),
        migrations.CreateModel(
            name='Butphe',
            fields=[
                ('ButPheID', models.AutoField(primary_key=True, serialize=False)),
                ('NoiDung', models.CharField(blank=True, max_length=255, null=True)),
                ('NgayButPhe', models.DateTimeField(blank=True, null=True)),
                ('MucDoKhan', models.BooleanField(default=False)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('VanBanDiID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.vanbandi')),
            ],
            options={
                'verbose_name_plural': 'Bút phê',
            },
        ),
        migrations.CreateModel(
            name='BaoCao',
            fields=[
                ('PhanHoiID', models.AutoField(primary_key=True, serialize=False)),
                ('NgayBaoCao', models.DateTimeField(blank=True, null=True)),
                ('LoaiBaoCao', models.CharField(blank=True, choices=[('TUAN', 'Báo cáo tuần'), ('THANG', 'Báo cáo tháng'), ('PHAN_HOI', 'Phản hồi')], max_length=50, null=True)),
                ('GhiChu', models.CharField(blank=True, max_length=255, null=True)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('VanBanDenID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.vanbanden')),
                ('VanBanDiID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.vanbandi')),
            ],
            options={
                'verbose_name_plural': 'Báo cáo / Phản hồi',
            },
        ),
    ]
