# Generated by Django 5.2.12 on 2026-04-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donvibenngoai',
            name='SoThuTu',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='donvibentrong',
            name='SoThuTu',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
