# Generated by Django 6.0.3 on 2026-04-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='GioiTinh',
            field=models.CharField(blank=True, choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='NgaySinh',
            field=models.DateField(blank=True, null=True),
        ),
    ]
