# Generated by Django 6.0.4 on 2026-04-20 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chuyentiep',
            name='NguoiChuyenTiepID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nguoi_chuyen_tiep', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chuyentiep',
            name='VanBanDenID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.vanbanden'),
        ),
        migrations.AlterField(
            model_name='chuyentiep',
            name='VanBanDiID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.vanbandi'),
        ),
    ]
