# Generated by Django 4.2.8 on 2026-04-14 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_donvibenngoai_sothutu_donvibentrong_sothutu'),
        ('web', '0002_useraccount_gioitinh_useraccount_ngaysinh'),
    ]

    operations = [
    ]
