# Generated by Django 5.2.12 on 2026-04-14 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_donvibenngoai_sothutu_donvibentrong_sothutu'),
        ('web', '0002_useraccount_gioitinh_useraccount_ngaysinh'),
    ]

    operations = [
    ]
