# Generated by Django 5.2.12 on 2026-04-14 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_merge_20260414_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lichsuhoatdong',
            name='DoiTuongID',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='lichsuhoatdong',
            name='LoaiDoiTuong',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='phancong',
            name='HanXuLy',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='phancong',
            name='TrangThaiXuLy',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vanbanden',
            name='NgayNhan',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='vanbanden',
            name='SoKyHieu',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='vanbanden',
            name='TrangThai',
            field=models.CharField(choices=[('MOI', 'Mới'), ('HOAN_THANH', 'Hoàn thành'), ('DANG_XU_LY', 'Đang xử lý')], db_index=True, default='MOI', max_length=50),
        ),
        migrations.AlterField(
            model_name='vanbandi',
            name='NgayBanHanh',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='vanbandi',
            name='SoKyHieu',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='vanbandi',
            name='TrangThai',
            field=models.CharField(choices=[('DU_THAO', 'Dự thảo'), ('CHO_PHE_DUYET', 'Chờ phê duyệt'), ('DA_PHE_DUYET', 'Đã phê duyệt'), ('DA_PHAT_HANH', 'Đã phát hành')], db_index=True, default='DU_THAO', max_length=50),
        ),
    ]
