# Generated by Django 4.2.8 on 2026-04-14 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_lichsuhoatdong_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='VanBanDiFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TepDinhKem', models.FileField(upload_to='di/%Y/%m/')),
                ('TenFile', models.CharField(blank=True, max_length=255, null=True)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('VanBanDiID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='web.vanbandi')),
            ],
        ),
    ]
