# Generated by Django 4.2.8 on 2026-04-14 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_lichsuhoatdong_userid'),
        ('web', '0004_alter_lichsuhoatdong_doituongid_and_more'),
    ]

    operations = [
    ]
