# Generated by Django 4.2.8 on 2026-04-14 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_merge_20260414_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vanbanden',
            name='NgayHoanThanh',
        ),
        migrations.AddField(
            model_name='vanbanden',
            name='DonViTrongID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.donvibentrong'),
        ),
        migrations.AlterField(
            model_name='baocao',
            name='VanBanDenID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.vanbanden'),
        ),
        migrations.AlterField(
            model_name='baocao',
            name='VanBanDiID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.vanbandi'),
        ),
        migrations.AlterField(
            model_name='chuyentiep',
            name='VanBanDenID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.vanbanden'),
        ),
        migrations.AlterField(
            model_name='chuyentiep',
            name='VanBanDiID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.vanbandi'),
        ),
        migrations.AlterField(
            model_name='lichsuhoatdong',
            name='DoiTuongID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lichsuhoatdong',
            name='LoaiDoiTuong',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='phancong',
            name='HanXuLy',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phancong',
            name='TrangThaiXuLy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vanbanden',
            name='NgayNhan',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vanbanden',
            name='SoKyHieu',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vanbanden',
            name='TrangThai',
            field=models.CharField(choices=[('HOAN_THANH', 'Hoàn thành'), ('DANG_XU_LY', 'Đang xử lý')], default='DANG_XU_LY', max_length=50),
        ),
        migrations.AlterField(
            model_name='vanbandi',
            name='NgayBanHanh',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vanbandi',
            name='SoKyHieu',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vanbandi',
            name='TrangThai',
            field=models.CharField(choices=[('DU_THAO', 'Dự thảo'), ('CHO_PHE_DUYET', 'Chờ phê duyệt'), ('DA_PHE_DUYET', 'Đã phê duyệt'), ('DA_PHAT_HANH', 'Đã phát hành')], default='DU_THAO', max_length=50),
        ),
    ]
