# Generated by Django 5.2.12 on 2026-04-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_vanbanden_trangthai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vanbanden',
            name='TrangThai',
            field=models.CharField(choices=[('MOI', 'Mới'), ('HOAN_THANH', 'Hoàn thành'), ('DANG_XU_LY', 'Đang xử lý')], db_index=True, default='DANG_XU_LY', max_length=50),
        ),
    ]
