# Generated by Django 4.2.8 on 2026-05-01 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_chuyentiep_nguoichuyentiepid_and_more'),
        ('web', '0006_alter_vanbanden_trangthai'),
        ('web', '0006_remove_vanbanden_ngayhoanthanh_and_more'),
    ]

    operations = [
    ]
