# Generated by Django 4.2.8 on 2026-05-01 02:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_merge_20260501_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chuyentiep',
            name='NguoiChuyenTiepID',
        ),
        migrations.AddField(
            model_name='donvibenngoai',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donvibenngoai',
            name='trang_thai',
            field=models.CharField(default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='donvibenngoai',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='donvibentrong',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donvibentrong',
            name='trang_thai',
            field=models.CharField(default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='donvibentrong',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccount',
            name='trang_thai',
            field=models.CharField(default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vanbanden',
            name='NgayHoanThanh',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lichsuhoatdong',
            name='UserID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='phancong',
            name='HanXuLy',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='phancong',
            name='TrangThaiXuLy',
            field=models.CharField(blank=True, choices=[('Đang xử lý', 'Đang xử lý'), ('Hoàn thành', 'Hoàn thành'), ('Quá hạn', 'Quá hạn')], db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vanbandi',
            name='NgayBanHanh',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='vanbandi',
            name='SoKyHieu',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='vanbandi',
            name='TrangThai',
            field=models.CharField(choices=[('DU_THAO', 'Dự thảo'), ('CHO_PHE_DUYET', 'Chờ phê duyệt'), ('DA_PHE_DUYET', 'Đã phê duyệt'), ('DA_PHAT_HANH', 'Đã phát hành')], db_index=True, default='DU_THAO', max_length=50),
        ),
        migrations.DeleteModel(
            name='VanBanDiFile',
        ),
    ]
