# Generated by Django 5.2.12 on 2026-05-01 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_remove_chuyentiep_nguoichuyentiepid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='PhongBan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.donvibentrong', verbose_name='Phòng ban'),
        ),
    ]
