# Generated by Django 5.2.12 on 2026-05-01 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_useraccount_phongban'),
    ]

    operations = [
        migrations.AddField(
            model_name='vanbandi',
            name='NguoiGui',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vanbandi_gui_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
