# Generated by Django 5.2.12 on 2026-05-01 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_vanbandi_nguoigui'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaitro',
            name='PhongBan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.donvibentrong', verbose_name='Thuộc phòng ban'),
        ),
    ]
