# Generated by Django 6.0.3 on 2026-05-02 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_vaitro_phongban'),
    ]

    operations = [
        migrations.AddField(
            model_name='vanbanden',
            name='VanBanDiID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vbd_link_set', to='web.vanbandi'),
        ),
        migrations.AlterField(
            model_name='vanbanden',
            name='DonViNgoaiID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.donvibenngoai'),
        ),
    ]
