# Generated by Django 5.2.12 on 2026-05-02 16:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_vanbanden_vanbandiid_alter_vanbanden_donvingoaiid'),
    ]

    operations = [
        migrations.AddField(
            model_name='baocao',
            name='HuongXuLy',
            field=models.CharField(blank=True, choices=[('SUA', 'Sửa văn bản'), ('CHUYEN', 'Chuyển người xử lý'), ('TU_CHOI', 'Từ chối báo cáo')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='baocao',
            name='NoiDungXuLy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baocao',
            name='RecipientID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baocao_nhan_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='baocao',
            name='ResolvedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baocao',
            name='TrangThai',
            field=models.CharField(choices=[('CHUA_XEM', 'Chưa xem'), ('DANG_XU_LY', 'Đang xử lý'), ('DA_GIAI_QUYET', 'Đã giải quyết')], default='CHUA_XEM', max_length=50),
        ),
        migrations.AddField(
            model_name='baocao',
            name='TrangThaiVBCu',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='baocao',
            name='LoaiBaoCao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='baocao',
            name='NgayBaoCao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='baocao',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baocao_gui_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vanbanden',
            name='TrangThai',
            field=models.CharField(choices=[('MOI', 'Mới'), ('HOAN_THANH', 'Hoàn thành'), ('DANG_XU_LY', 'Đang xử lý'), ('CAN_XU_LY_LAI', 'Cần xử lý lại')], db_index=True, default='DANG_XU_LY', max_length=50),
        ),
        migrations.AlterField(
            model_name='vanbandi',
            name='TrangThai',
            field=models.CharField(choices=[('DU_THAO', 'Dự thảo'), ('CHO_PHE_DUYET', 'Chờ phê duyệt'), ('DA_PHE_DUYET', 'Đã phê duyệt'), ('DA_PHAT_HANH', 'Đã phát hành'), ('CAN_SUA_DOI', 'Cần sửa đổi'), ('CAN_XU_LY_LAI', 'Cần xử lý lại')], db_index=True, default='DU_THAO', max_length=50),
        ),
    ]
