# Generated by Django 5.2.12 on 2026-05-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_baocao_huongxuly_baocao_noidungxuly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vanbandi',
            name='NgayGuiPheDuyet',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vanbandi',
            name='NgayPhatHanh',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vanbandi',
            name='NgayPheDuyet',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vanbanden',
            name='TrangThai',
            field=models.CharField(choices=[('MOI', 'Mới'), ('HOAN_THANH', 'Hoàn thành'), ('DANG_XU_LY', 'Đang xử lý'), ('CAN_XU_LY_LAI', 'Cần xử lý lại'), ('CHO_PHE_DUYET', 'Chờ phê duyệt'), ('DA_PHE_DUYET', 'Đã phê duyệt'), ('DA_PHAT_HANH', 'Đã phát hành')], db_index=True, default='DANG_XU_LY', max_length=50),
        ),
    ]
